// modified-2026-09-17
/**
 * API: Download Optimized Image File
 *
 * GET /api/images/:id/download
 *
 * Serves the actual WebP image generated by Sharp for preview and download.
 *
 * Security:
 * - Validates authentication via Shopify session or shop scope
 * - Enforces multi-tenant isolation (image must belong to authenticated shop)
 * - Protects against path traversal via strict ID sanitization
 */

import type { LoaderFunctionArgs } from "@remix-run/node";
import { authenticate } from "../shopify.server";
import { db } from "../db.server";
import fs from "fs";
import path from "path";

export const loader = async ({ request, params }: LoaderFunctionArgs) => {
  const { session } = await authenticate.admin(request);
  const shopDomain = session.shop;
  const imageId = params.id;

  if (!imageId || !/^[a-zA-Z0-9_-]+$/.test(imageId)) {
    return new Response("Invalid image ID", { status: 400 });
  }

  const shopRecord = await db.shop.findFirst({
    where: { shopDomain },
  });

  if (!shopRecord) {
    return new Response("Shop not found", { status: 404 });
  }

  const image = await db.productImage.findFirst({
    where: { id: imageId, shopId: shopRecord.id },
    include: { optimizationResult: true },
  });

  if (!image) {
    return new Response("Image not found or not owned by shop", { status: 404 });
  }

  const safeImageId = imageId.replace(/[^a-zA-Z0-9-_]/g, "_");
  const storagePath = process.env.OPTIMIZED_STORAGE_PATH ?? "./tmp/optimized";
  const filePath = path.resolve(storagePath, shopRecord.id, `${safeImageId}.webp`);

  if (!fs.existsSync(filePath)) {
    return new Response("Optimized image file not found on disk", { status: 404 });
  }

  const fileBuffer = fs.readFileSync(filePath);
  const safeFilename = `${image.productTitle.replace(/[^a-zA-Z0-9_-]/g, "_")}_optimized.webp`;

  return new Response(fileBuffer, {
    status: 200,
    headers: {
      "Content-Type": "image/webp",
      "Content-Disposition": `attachment; filename="${safeFilename}"`,
      "Content-Length": String(fileBuffer.length),
      "Cache-Control": "private, max-age=3600",
    },
  });
};
